title: Comptine
description: La Compta qui Chante !
url: ""
baseurl: "/comptine"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Custom variables
github_repo: https://github.com/MartinDelille/comptine
latest_release: https://github.com/MartinDelille/comptine/releases/latest

platforms:
  - icon: "üçé"
    name: "MacOS"
    url: "https://github.com/MartinDelille/comptine/releases/latest/download/Comptine-MacOS.dmg"
    requirements: "MacOS 11 (Big Sur) ou plus r√©cent"
    button: "T√©l√©charger .dmg"
  - icon: "ü™ü"
    name: "Windows"
    url: "https://github.com/MartinDelille/comptine/releases/latest/download/Comptine-Windows.exe"
    requirements: "Windows 10 ou plus r√©cent"
    button: "T√©l√©charger .exe"
  - icon: "üêß"
    name: "Linux"
    url: "https://github.com/MartinDelille/comptine/releases/latest/download/Comptine-x86_64.AppImage"
    requirements: "Ubuntu 22.04 ou √©quivalent"
    button: "T√©l√©charger .AppImage"

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
